import { useMemo, useState } from "react";
import { Activity, Gauge, ShieldCheck, TriangleAlert } from "lucide-react";
import { PageLayout } from "@/components/PageLayout";
import { NitinControls } from "@/components/nitinBhaiya/NitinControls";
import { NitinTimelineTable } from "@/components/nitinBhaiya/NitinTimelineTable";
import { SignalBadge } from "@/components/nitinBhaiya/SignalBadge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { LastRefreshBadge } from "@/components/LastRefreshBadge";
import { SEO } from "@/components/SEO";
import { useNitinBhaiyaAnalysis } from "@/hooks/useNitinBhaiyaAnalysis";
import { formatIndianNumber } from "@/lib/formatNumber";
import { ChainStrike, classifyActivity } from "@/utils/nitinBhaiyaEngine";

const tone = (value: string) => value.includes("BULLISH") ? "text-success" : value.includes("BEARISH") ? "text-destructive" : "text-primary";
const n = (value: number) => formatIndianNumber(Math.round(value));

export default function NitinBhaiyaTerminal() {
  const state = useNitinBhaiyaAnalysis();
  const [selected, setSelected] = useState<ChainStrike | null>(null);
  const baselineMap = useMemo(() => new Map(state.baseline.map((row) => [row.strike, row])), [state.baseline]);
  const rows = useMemo(() => { const index = state.current.findIndex((row) => row.strike === state.engine.atm); return state.current.slice(Math.max(0, index - 7), index + 8); }, [state.current, state.engine.atm]);
  return <PageLayout showFooter={false}>
    <SEO title="NitinBhaiya Live Terminal | OptionWorld" description="Live NSE option chain confluence terminal with writer, decay, IV and COI analysis." path="/nitinbhaiya" />
    <section className="mx-auto w-full max-w-[1600px] py-3">
      <div className="flex items-start justify-between gap-3 px-3 pb-3"><div><p className="font-mono text-[10px] uppercase text-primary">NitinBhaiya Intelligence</p><h1>Live Option Chain Terminal</h1><p className="text-muted-foreground">Seven independent checks. One disciplined confluence view.</p></div>{state.lastRefresh && <LastRefreshBadge lastRefresh={state.lastRefresh} />}</div>
      <NitinControls symbols={state.symbols} expiries={state.expiries} symbol={state.symbol} expiry={state.expiry} date={state.date} time={state.time} loading={state.loading} onSymbol={state.setSymbol} onExpiry={state.setExpiry} onDate={state.setDate} onTime={state.setTime} onRefresh={() => state.refresh()} />
      {state.error && <div className="m-3 border border-destructive/40 bg-destructive/10 p-3 text-destructive"><TriangleAlert className="mr-2 inline h-4 w-4" />{state.error}</div>}
      <div className="grid grid-cols-2 gap-px bg-border border-y lg:grid-cols-5">
        {[['Spot', state.current[0]?.spot?.toFixed(2) ?? '—'], ['ATM', state.engine.atm ? n(state.engine.atm) : '—'], ['PCR (COI)', state.engine.pcrCoi?.toFixed(2) ?? '—'], ['Confluence', `${state.engine.score >= 0 ? '+' : ''}${state.engine.score.toFixed(1)} / 50`], ['Sentiment', state.engine.sentiment]].map(([label, value]) => <div key={label} className="bg-card p-3"><p className="text-[10px] uppercase text-muted-foreground">{label}</p><p className={`mt-1 font-mono text-base font-bold ${label === 'Sentiment' ? tone(value) : ''}`}>{value}</p></div>)}
      </div>
      <div className="grid gap-3 p-3 xl:grid-cols-[1fr_340px]">
        <Card className="overflow-hidden rounded-none"><CardHeader className="py-3"><CardTitle className="flex items-center justify-between text-sm"><span>Option Chain · ATM ±7</span><span className="font-mono text-[10px] text-muted-foreground">Click a row for Greeks</span></CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-[10px]"><thead className="bg-muted"><tr>{['CE SIGNAL','CE OI','CE COI','CE LTP','CE IV','STRIKE','PE IV','PE LTP','PE COI','PE OI','PE SIGNAL'].map((h) => <th key={h} className="px-1 py-2 text-center font-semibold">{h}</th>)}</tr></thead><tbody>{rows.map((row) => { const base = baselineMap.get(row.strike); const ceActivity = classifyActivity(row.ce.coi, base ? row.ce.ltp - base.ce.ltp : 0); const peActivity = classifyActivity(row.pe.coi, base ? row.pe.ltp - base.pe.ltp : 0); return <tr key={row.strike} onClick={() => setSelected(row)} className={`cursor-pointer border-t hover:bg-muted/50 ${row.strike === state.engine.atm ? 'bg-[hsl(var(--oc-atm-bg))]' : ''}`}><td className="px-1 py-1.5 text-center">{ceActivity}</td><td className="px-1 py-1.5 text-right font-mono">{n(row.ce.oi)}</td><td className="px-1 py-1.5 text-right font-mono">{n(row.ce.coi)}</td><td className="px-1 py-1.5 text-right font-mono">{row.ce.ltp.toFixed(2)}</td><td className="px-1 py-1.5 text-right font-mono">{row.ce.iv.toFixed(2)}</td><td className="bg-muted/70 px-2 py-1.5 text-center font-mono font-bold">{n(row.strike)}</td><td className="px-1 py-1.5 text-right font-mono">{row.pe.iv.toFixed(2)}</td><td className="px-1 py-1.5 text-right font-mono">{row.pe.ltp.toFixed(2)}</td><td className="px-1 py-1.5 text-right font-mono">{n(row.pe.coi)}</td><td className="px-1 py-1.5 text-right font-mono">{n(row.pe.oi)}</td><td className="px-1 py-1.5 text-center">{peActivity}</td></tr>; })}</tbody></table></div></CardContent></Card>
        <div className="space-y-3"><Card className="rounded-none"><CardHeader className="py-3"><CardTitle className="text-sm">Market Structure</CardTitle></CardHeader><CardContent className="grid grid-cols-3 gap-2 text-center"><div><p className="text-muted-foreground">Support</p><p className="font-mono font-bold text-success">{state.engine.support ? n(state.engine.support.strike) : '—'}</p></div><div><p className="text-muted-foreground">ATM</p><p className="font-mono font-bold text-primary">{n(state.engine.atm)}</p></div><div><p className="text-muted-foreground">Resistance</p><p className="font-mono font-bold text-destructive">{state.engine.resistance ? n(state.engine.resistance.strike) : '—'}</p></div></CardContent></Card>
        <Card className="rounded-none"><CardHeader className="py-3"><CardTitle className="flex items-center gap-2 text-sm"><Gauge className="h-4 w-4" />Seven-engine panel</CardTitle></CardHeader><CardContent className="space-y-2">{state.engine.signals.map((signal) => <div key={signal.key} className="grid grid-cols-[1fr_auto] gap-2 border-b pb-2"><div><p className="font-semibold">{signal.label} <span className="text-muted-foreground">{Math.round(signal.weight * 100)}%</span></p><p className="text-[10px] text-muted-foreground">{signal.detail}</p></div>{signal.available ? <SignalBadge direction={signal.direction} /> : <span className="text-[10px] text-muted-foreground">N/A</span>}</div>)}</CardContent></Card></div>
      </div>
      <div className="grid gap-px border-y bg-border sm:grid-cols-2"><div className="bg-card p-4"><p className="text-[10px] uppercase text-muted-foreground">Writer Signal</p><div className="mt-2 flex items-center gap-2"><ShieldCheck className="h-4 w-4" /><SignalBadge direction={state.engine.writerSignal} /></div><p className="mt-2 text-muted-foreground">OI ↑ + Premium ↓ + IV ↓ activity at ATM.</p></div><div className="bg-card p-4"><p className="text-[10px] uppercase text-muted-foreground">Relative Decay Signal</p><div className="mt-2 flex items-center gap-2"><Activity className="h-4 w-4" /><SignalBadge direction={state.engine.decaySignal} /></div><p className="mt-2 font-mono text-muted-foreground">CE {state.engine.ceDecay?.toFixed(2) ?? '—'}% · PE {state.engine.peDecay?.toFixed(2) ?? '—'}%</p></div></div>
      <NitinTimelineTable symbol={state.symbol} expiry={state.expiry} date={state.date} time={state.time} baseline={state.baseline} refreshKey={state.lastRefresh?.getTime() ?? 0} />
    </section>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent><DialogHeader><DialogTitle>Strike {selected?.strike}</DialogTitle></DialogHeader>{selected && <div className="grid grid-cols-2 gap-3 text-xs"><div><h3 className="mb-2 text-destructive">CALL</h3><p>Delta {selected.ce.delta.toFixed(4)}</p><p>Gamma {selected.ce.gamma.toFixed(4)}</p><p>Theta {selected.ce.theta.toFixed(4)}</p><p>Vega {selected.ce.vega.toFixed(4)}</p></div><div><h3 className="mb-2 text-success">PUT</h3><p>Delta {selected.pe.delta.toFixed(4)}</p><p>Gamma {selected.pe.gamma.toFixed(4)}</p><p>Theta {selected.pe.theta.toFixed(4)}</p><p>Vega {selected.pe.vega.toFixed(4)}</p></div></div>}</DialogContent></Dialog>
  </PageLayout>;
}